/*
This file was generated by BMPload.exe from Reach Technology on Mon Oct 30 00:23:32 2017
 from the file C:\Users\Jason\Desktop\SJSU\CMPE 240\project\test\testMac.mac

This file displays each macro name with its assigned macro number.

Include this file in the host control program.
*/

#define load_bar_full 1
#define display_login_page 2
#define ONE 3
#define TWO 4
#define THREE 5
#define FOUR 6
#define FIVE 7
#define SIX 8
#define SEVEN 9
#define EIGHT 10
#define NINE 11
#define main_page 12
#define volume_up 13
#define volume_down 14
#define define_hotspots_temperature 15
