/*
This file was generated by BMPload.exe from Reach Technology on Fri Nov 17 08:03:16 2017
 from the file C:\Users\Jason\Desktop\SJSU\CMPE 240\github\brainstorm\macros\Project_Macros_1.0.mac

This file displays each macro name with its assigned macro number.

Include this file in the host control program.
*/

#define show_splash 1
#define load_bar_full 2
#define display_login_page 3
#define define_hotspots_login 4
#define ONE 5
#define TWO 6
#define THREE 7
#define FOUR 8
#define FIVE 9
#define SIX 10
#define SEVEN 11
#define EIGHT 12
#define NINE 13
#define display_asterik_1 14
#define display_asterik_2 15
#define display_asterik_3 16
#define display_asterik_4 17
#define display_login_attempts_left 18
#define display_locked_page 19
#define display_main_page 20
#define logout_button 21
#define setting_button 22
#define temp_hotspot 23
#define motor_hotspot 24
#define laser_hotspot 25
#define display_temp_page 26
#define temp_unit_f 27
#define temp_unit_c 28
#define main_button 29
#define display_motor_page 30
#define display_laser_page 31
#define text_display 32
#define speed_up 33
#define speed_down 34
#define set_uid 35
#define display_uid 36
#define display_settings_screen 37
#define display_slider 38
#define adjust_brightness 39
#define display_game_page 40
#define stone_display 41
#define add_point 42
#define win 43
#define lose 44
#define start 45
