/*
This file was generated by BMPload.exe from Reach Technology on Tue Oct 10 20:27:52 2017
 from the file C:\Users\crdavila\Documents\School\Fall_17\CMPE240\brainstorm\macros\Project_Macros_1.0.mac

This file displays each macro name with its assigned macro number.

Include this file in the host control program.
*/

#define show_splash 1
#define load_bar_full 2
#define load_bar 3
