/*
This file was generated by BMPload.exe from Reach Technology on Tue Oct 31 20:29:38 2017
 from the file C:\Users\crdavila\Documents\School\Fall_17\CMPE240\brainstorm\macros\Project_Macros_1.0.mac

This file displays each macro name with its assigned macro number.

Include this file in the host control program.
*/

#define show_splash 1
#define load_bar_full 2
#define display_login_page 3
#define define_hotspots_login 4
#define ONE 5
#define TWO 6
#define THREE 7
#define FOUR 8
#define FIVE 9
#define SIX 10
#define SEVEN 11
#define EIGHT 12
#define NINE 13
#define define_hotspots_temperature 14
#define define_hotspots_laser 15
#define define_hotspots_motor 16
